import { InferSchemaType, Schema, model } from "mongoose";

/* eslint-disable no-unused-vars */
export enum UserType {
  Student = "STUDENT",
  Alumni = "ALUMNI",
  Admin = "ADMIN",
}
/* eslint-enable no-unused-vars */

const userSchema = new Schema({
  _id: {
    // ID generated by Google Oauth, must be called _id to be queried with .findById()
    type: String,
  },
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
  },
  // Pass in from google
  name: {
    type: String,
    required: true,
    trim: true,
  },
  profilePicture: {
    type: String,
    required: true,
    trim: true,
  },
  type: {
    type: String,
    required: true,
    enum: Object.values(UserType),
    default: UserType.Student,
  },
  linkedIn: {
    type: String,
    required: false,
    trim: true,
  },
  phoneNumber: {
    type: String,
    required: false,
    trim: true,
  },
  hobbies: {
    type: [String],
    default: [],
  },
  skills: {
    type: [String],
    default: [],
  },
  // Only for students
  major: {
    type: String,
    required: false,
    trim: true,
  },
  classLevel: {
    type: String,
    required: false, // also eventually an enum?
  },
  school: {
    type: String,
    required: false,
    trim: true,
  },
  fieldOfInterest: {
    type: [String],
    default: [],
  },
  projects: {
    type: [String],
    default: [],
  },

  companiesOfInterest: {
    type: [String],
    default: [],
  },
  // Only for alumni
  position: {
    type: String,
    required: false,
    trim: true,
  },
  company: {
    type: String,
    required: false,
    trim: true,
  },
  shareProfile: {
    type: Boolean,
    required: false,
  },
  organizations: {
    type: [String],
    required: true,
  },
  specializations: {
    type: [String],
    required: true,
  },
});

// Add indexes for better performance
userSchema.index({ type: 1, shareProfile: 1 }); // Alumni search
userSchema.index({ company: "text" }); // Company filtering
userSchema.index({ name: "text" }); // Name search
userSchema.index({ position: "text" }); // Position search

type User = InferSchemaType<typeof userSchema>;

export default model<User>("User", userSchema);
