import { InferSchemaType, Schema, model } from "mongoose";

/* eslint-disable no-unused-vars */
export enum UserType {
  Student = "STUDENT",
  Alumni = "ALUMNI",
  Admin = "ADMIN",
}

/* eslint-disable no-unused-vars */
export enum MajorType {
  Anthropology = "Anthropology",
  Artificial_Intelligence = "Artificial Intelligence",
  Astronomy_and_Astrophysics = "Astronomy and Astrophysics",
  Bioengineering = "Bioengineering",
  Biology = "Biology",
  Black_Diaspora_and_African_American_Studies = "Black Diaspora and African American Studies",
  Chemical_Engineering = "Chemical Engineering",
  Chemistry_and_Biochemistry = "Chemistry and Biochemistry",
  Chicanx_and_Latinx_Studies = "Chicanx and Latinx Studies",
  Chinese_Studies = "Chinese Studies",
  Cinematic_Arts = "Cinematic Arts",
  Classical_Studies = "Classical Studies",
  Cognitive_Science = "Cognitive Science",
  Communication = "Communication",
  Computer_Engineering_CSE = "Computer Engineering (CSE)",
  Computer_Engineering_ECE = "Computer Engineering (ECE)",
  Computer_Science = "Computer Science",
  Critical_Gender_Studies = "Critical Gender Studies",
  Data_Science = "Data Science",
  Economics = "Economics",
  Education_Studies = "Education Studies",
  Electrical_Engineering = "Electrical Engineering",
  Environmental_Systems = "Environmental Systems",
  Ethnic_Studies = "Ethnic Studies",
  German_Studies = "German Studies",
  Global_Health = "Global Health",
  Global_South_Studies = "Global South Studies",
  History = "History",
  Human_Developmental_Sciences = "Human Developmental Sciences",
  International_Studies = "International Studies",
  Italian_Studies = "Italian Studies",
  Japanese_Studies = "Japanese Studies",
  Jewish_Studies = "Jewish Studies",
  Latin_American_Studies = "Latin American Studies",
  Linguistics = "Linguistics",
  Literature = "Literature",
  Marine_Biology = "Marine Biology",
  Mathematics = "Mathematics",
  Mechanical_and_Aerospace_Engineering = "Mechanical and Aerospace Engineering",
  Music = "Music",
  Nanoengineering = "Nanoengineering",
  Oceanography = "Oceanography",
  Philosophy = "Philosophy",
  Physics = "Physics",
  Political_Science = "Political Science",
  Psychology = "Psychology",
  Public_Health = "Public Health",
  Religion = "Religion",
  Russian_and_Soviet_Studies = "Russian and Soviet Studies",
  Sociology = "Sociology",
  Structural_Engineering = "Structural Engineering",
  Theater_and_Dance = "Theater and Dance",
  Urban_Studies = "Urban Studies",
  Visual_Arts = "Visual Arts",
}

/* eslint-enable no-unused-vars */
const userSchema = new Schema({
  _id: {
    // ID generated by Google Oauth, must be called _id to be queried with .findById()
    type: String,
  },
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
  },
  // Pass in from google
  name: {
    type: String,
    required: true,
    trim: true,
  },
  profilePicture: {
    type: String,
    required: true,
    trim: true,
  },
  type: {
    type: String,
    required: true,
    enum: Object.values(UserType),
    default: UserType.Student,
  },
  linkedIn: {
    type: String,
    required: false,
    trim: true,
  },
  phoneNumber: {
    type: String,
    required: false,
    trim: true,
  },
  hobbies: {
    type: [String],
    default: [],
  },
  skills: {
    type: [String],
    default: [],
  },
  // Only for students
  major: {
    type: String,
    required: false,
    enum: Object.values(MajorType),
    trim: true,
  },
  classLevel: {
    type: String,
    required: false, // also eventually an enum?
  },
  school: {
    type: String,
    required: false,
    trim: true,
  },
  fieldOfInterest: {
    type: [String],
    default: [],
  },
  projects: {
    type: [String],
    default: [],
  },

  companiesOfInterest: {
    type: [String],
    default: [],
  },
  // Only for alumni
  position: {
    type: String,
    required: false,
    trim: true,
  },
  company: {
    type: String,
    required: false,
    trim: true,
  },
  shareProfile: {
    type: Boolean,
    required: false,
  },
  organizations: {
    type: [String],
    required: true,
  },
  specializations: {
    type: [String],
    required: true,
  },
});

// Add indexes for better performance
userSchema.index({ type: 1, shareProfile: 1 }); // Alumni search
userSchema.index({ company: "text" }); // Company filtering
userSchema.index({ name: "text" }); // Name search
userSchema.index({ position: "text" }); // Position search

type User = InferSchemaType<typeof userSchema>;

export default model<User>("User", userSchema);
